name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  precheck:
    name: Precheck
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Version
        id: vars
        shell: bash
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Commit version
        run: |
          echo ${{ github.event.inputs.version }} > VERSION
          git add VERSION
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git commit -a -m "Releasing version ${{ github.event.inputs.version }}"
          git push origin main

  release:
    name: Release
    needs: [ precheck ]
    permissions:
      contents: write
      id-token: write
      actions: read
      packages: write
    uses: jreleaser/jreleaser-slsa/.github/workflows/builder_slsa3_zig.yml@v1.1.0
    with:
      project-version: ${{ needs.precheck.outputs.VERSION }}
      jreleaser-version: early-access
      rekor-log-public: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
